language: node_js
group: edge
sudo: required
services:
  - mongodb
  - docker
node_js:
  - "0.10"
  - "4.4.3"
before_script:
  - sleep 15
before_install:
  - npm install -g bower
  - export PHANTOMJS_CDNURL=https://bitbucket.org/ariya/phantomjs/downloads npm install phantomjs
  - npm install -g phantomjs
  - npm install fh-build -g
  - fh-build template
install: npm install

